{% set version = "0.13.0" %}

package:
  name: odil
  version: {{ version }}

source:
  url: https://github.com/lamyj/odil/archive/v{{ version }}.tar.gz
  sha256: 0f78095600f6348cd53d9c04d1659beca5d6d01cd189a443655941229b903b5e
  patches:
    # backport https://github.com/lamyj/odil/commit/4a64df2c2a38a2f7dc9be2c2732b82a6f38496e8
    - patches/0001-Fix-module-type.patch
    # backport https://github.com/lamyj/odil/commit/4a64df2c2a38a2f7dc9be2c2732b82a6f38496e8
    - patches/0002-Fix-type-in-wrappers.patch
    # partial backport of https://github.com/lamyj/odil/commit/676f9f30cff80c2c941e06cd7bcc3a89e07f9517
    - patches/0003-fix-windows-build.patch
    # backport https://github.com/lamyj/odil/commit/0b72379de94b53100a8a8af9eb49e92bafce8ed7
    - patches/0004-Add-missing-header.patch
    # backport https://github.com/lamyj/odil/commit/b9b48a2
    - patches/0005-Fix-boost-asio-1.87.patch

build:
  number: 5

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libboost-devel
    - dcmtk
    - icu
    - jsoncpp
    - pybind11
    - python
    - zlib
  run:
    - python

test:
  imports:
    - odil

about:
  home: https://github.com/lamyj/odil
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Library for the DICOM standard

  description: |
    Odil is a C++11 library for the DICOM standard.

    Odil leverages C++ constructs to provide a user-friendly API of the different parts of the DICOM standard. Included in Odil are:
    - Reading and writing data sets with any transfer syntax
    - Standard JSON and XML representation of datasets
    - Clients and servers for the various DICOM protocols (C-FIND, C-GET, C-MOVE, C-STORE)
    - Implementation of the DICOM web-services (WADO-RS, QIDO-RS, STOW-RS)
    - Conversion to and from DCMTK data structures.

  doc_url: https://odil.readthedocs.io/
  dev_url: https://github.com/lamyj/odil

extra:
  recipe-maintainers:
    - lamyj
