{% set version = "0.12.2" %}

package:
  name: odil
  version: {{ version }}

source:
  url: https://github.com/lamyj/odil/archive/v{{ version }}.tar.gz
  sha256: 717be4d42b69ed6060d984e7966ccc1081db957cc54fd1e90ffbdf47c18321cb

build:
  number: 8
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libboost-devel
    - icu
    - jsoncpp
    - pybind11
    - python
  run:
    - python

test:
  imports:
    - odil

about:
  home: https://github.com/lamyj/odil
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Library for the DICOM standard

  description: |
    Odil is a C++11 library for the DICOM standard.

    Odil leverages C++ constructs to provide a user-friendly API of the different parts of the DICOM standard. Included in Odil are:
    - Reading and writing data sets with any transfer syntax
    - Standard JSON and XML representation of datasets
    - Clients and servers for the various DICOM protocols (C-FIND, C-GET, C-MOVE, C-STORE)
    - Implementation of the DICOM web-services (WADO-RS, QIDO-RS, STOW-RS)
    - Conversion to and from DCMTK data structures.

  doc_url: https://odil.readthedocs.io/
  dev_url: https://github.com/lamyj/odil

extra:
  recipe-maintainers:
    - lamyj
