{% set version = "0.13.0" %}

package:
  name: odil
  version: {{ version }}

source:
  url: https://github.com/lamyj/odil/archive/v{{ version }}.tar.gz
  sha256: 0f78095600f6348cd53d9c04d1659beca5d6d01cd189a443655941229b903b5e
  patches:
    - fix-module-type.patch
    - ssize_t.patch
    - windows_build.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - libboost-devel
    - dcmtk
    - icu
    - jsoncpp
    - pybind11
    - python
    - zlib
  run:
    - python

test:
  imports:
    - odil

about:
  home: https://github.com/lamyj/odil
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Library for the DICOM standard

  description: |
    Odil is a C++11 library for the DICOM standard.

    Odil leverages C++ constructs to provide a user-friendly API of the different parts of the DICOM standard. Included in Odil are:
    - Reading and writing data sets with any transfer syntax
    - Standard JSON and XML representation of datasets
    - Clients and servers for the various DICOM protocols (C-FIND, C-GET, C-MOVE, C-STORE)
    - Implementation of the DICOM web-services (WADO-RS, QIDO-RS, STOW-RS)
    - Conversion to and from DCMTK data structures.

  doc_url: https://odil.readthedocs.io/
  dev_url: https://github.com/lamyj/odil

extra:
  recipe-maintainers:
    - lamyj
