{% set name = "odil" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lamyj/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 001448ea18ce593ded5744b8755845520f71bbc9571dcee25161fe4cab936693
  patches:
    - windows_boost_system_and_python.patch  # [win]

build:
  number: 0
  skip: true  # [py<=35 or (win and vc<14)]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - boost
    - icu
    - jsoncpp
    - pybind11
    - python
  run:
    - boost-cpp
    - python

test:
  imports:
    - odil

about:
  home: https://github.com/lamyj/{{ name|lower }}
  license: CECILL-B
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Library for the DICOM standard

  description: |
    Odil is a C++11 library for the DICOM standard.

    Odil leverages C++ constructs to provide a user-friendly API of the different parts of the DICOM standard. Included in Odil are:
    - Reading and writing data sets with any transfer syntax
    - Standard JSON and XML representation of datasets
    - Clients and servers for the various DICOM protocols (C-FIND, C-GET, C-MOVE, C-STORE)
    - Implementation of the DICOM web-services (WADO-RS, QIDO-RS, STOW-RS)
    - Conversion to and from DCMTK data structures.

  doc_url: https://{{ name|lower }}.readthedocs.io/
  dev_url: https://github.com/lamyj/{{ name|lower }}

extra:
  recipe-maintainers:
    - lamyj
